#!/bin/bash

### Note ###
#This script takes all the read count files generated by STAR and collates them into a single read count file that can be important into R.

DIRin=/malabar/07_larval_analysis/02_Read_mapping/

#Changing into work directory
cd ${inDir}

#creating a file with just the first column containing the gene names and adding "Sample" to the top
rm STAR_gene_counts.tsv
init=(*)
#echo -e "Sample\n${init}" | awk '{ print $1 }' > STAR_gene_counts.tsv
echo -e "Sample\n$(cat ${init}/*Gene*tab | tail -n +5)" | awk '{ print $1 }' > STAR_gene_counts.tsv


for name in *; do
	echo $name
	if [ ${name} != "STAR_gene_counts.tsv" ]
	then
		join -t $'\t' STAR_gene_counts.tsv <( echo -e "Sample\t${name}\t${name}\t${name}\n$(cat ${name}/*Gene*tab | tail -n +5)" | awk -v OFS='\t' '{ print $1, $2 }')  >> STAR_gene_counts.tmp
		mv STAR_gene_counts.tmp STAR_gene_counts.tsv
	fi
done
