---
title: "Coseq_clustering"
author: "RH"
date: "2023-01-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#====================================================================================================
### Coseq clustering method ###
#====================================================================================================

# Load packages
```{r}
library(coseq)
library(tidyverse)
```

# Getting significant genes
```{r}

padj.cutoff <- 0.001

sig_lrt_genes_0.001 <- res_lrt %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble() %>% 
  filter(padj < padj.cutoff)
  
nrow(sig_lrt_genes_0.001)

candidate_genes <- pull(sig_lrt_genes_0.001, "gene")
length(candidate_genes)

coseq_counts <- as.data.frame(count_data) %>%
  rownames_to_column("gene") %>%
  filter(gene %in% candidate_genes) %>% column_to_rownames("gene")

coseq_counts_norm <- as.data.frame(counts(dds, normalized=TRUE)) %>%
  rownames_to_column("gene") %>%
  filter(gene %in% candidate_genes) %>% column_to_rownames("gene")


stages <- factor(sample_table$Stage)
```

# running coseq on DESeq normalised data with arcsin
```{r}
res_coseq <- coseq(coseq_counts_norm, K = 2:20, normFactors = "none", model = "Normal", transformation = "arcsin", parallel= FALSE, seed = 1234, iter=10000)

summary(res_coseq)
table(clusters(res_coseq))
plot(res_coseq)
plot(res_coseq, graphs="boxplots", conds=stages, collapse_reps = "sum")
```

# Pulling out specific clusters to remove for focussed analysis
```{r}
clusters <- clusters(res_coseq) %>% as.data.frame() %>% rownames_to_column("gene")
names(clusters)[2] <- "clusters"

genes_improved <- as.vector((clusters[clusters$clusters %in% c("1", "4", "6", "7", "8", "9", "14"), ])[,-2])
length(genes_improved)

coseq_counts_improved <- as.data.frame(coseq_counts_norm) %>%
  rownames_to_column("gene") %>%
  filter(gene %in% genes_improved) %>% column_to_rownames("gene")

res_coseq_improved <- coseq(coseq_counts_improved, K = 2:10, normFactors = "none", model = "Normal", transformation = "arcsin", parallel= FALSE, seed = 1234, iter=10000)

summary(res_coseq_improved)
plot(res_coseq_improved, graphs="boxplots", conds=stages, collapse_reps = "sum")

```
# Further refinement to create figure for publication
```{r}
clusters_refined <- clusters(res_coseq_improved) %>% as.data.frame() %>% rownames_to_column("gene")
names(clusters_refined)[2] <- "clusters"

genes_improved_refined <- as.vector((clusters_refined[clusters_refined$clusters %in% c("1", "3", "6", "7"), ])[,-2])
length(genes_improved_refined)

coseq_counts_improved_refined <- as.data.frame(coseq_counts_norm) %>%
                         rownames_to_column("gene") %>%
                         filter(gene %in% genes_improved_refined) %>% column_to_rownames("gene")

res_coseq_improved_refined <- coseq(coseq_counts_improved_refined, K = 2:8, normFactors = "none", model = "Normal", transformation = "arcsin", parallel= FALSE, seed = 1234, iter=10000)

summary(res_coseq_improved_refined)
plot(res_coseq_improved_refined, graphs="boxplots", conds=stages, collapse_reps = "sum")
cluster.plot.publication <- plot(res_coseq_improved_refined, graphs="boxplots", conds=stages, collapse_reps = "sum")

cluster.plot.publication$boxplots  + theme_bw()

# saving as jpeg and pdf
jpeg("02_Outputs/cluster.plot.publication.jpg", quality = 100)
cluster.plot.publication$boxplots  + theme_bw()
dev.off()
pdf("02_Outputs/cluster.plot.publication.pdf", width = 7, height = 5)
cluster.plot.publication$boxplots  + theme_bw()
dev.off()

cluster.plot.publication$boxplots

```

#Getting gene annotations for clusters
```{r}
clusters.select <- clusters(res_coseq_improved_refined) %>% as.data.frame() %>% rownames_to_column("gene")
names(clusters.select)[2] <- "clusters"

anot_temp <- as.data.frame(annotation)
colnames(anot_temp )[1] <- "gene"


write_tsv(clusters.select %>%
            left_join(sig_lrt_genes_0.001, by = "gene") %>%
            left_join(anot_temp, by = "gene"),
          "02_Outputs/D3_D31_clusters_annotated.tsv")

```
